import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View, type TextInputProps, TextInput } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import type { ReactNode } from "react";
import { useWorkspace } from "../state/Workspace";

export function Screen({ title, children, loading = false, refresh, error }: { title: string; children: ReactNode; loading?: boolean; refresh?: () => void; error?: string }) {
  const workspace = useWorkspace();
  return <SafeAreaView edges={["top"]} style={styles.root}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={refresh ? <RefreshControl refreshing={loading} onRefresh={refresh} tintColor="#245d4b"/> : undefined}><Text style={styles.eyebrow}>VORYLEN</Text><Text style={styles.title}>{title}</Text>{workspace.signedIn && <><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.workspaceList}>{workspace.organizations.map(item => <Pressable accessibilityRole="button" accessibilityState={{ selected: workspace.organization === item.id }} key={item.id} onPress={() => workspace.selectOrganization(item.id)} style={[styles.chip, workspace.organization === item.id && styles.selected]}><Text style={styles.text}>{item.name}</Text></Pressable>)}</ScrollView>{!workspace.organization && <Text style={styles.text}>No accessible organization yet. Complete setup on the web, then sign in again.</Text>}</>}{(error || workspace.error) ? <Text accessibilityRole="alert" style={styles.error}>{error || workspace.error}</Text> : null}{children}</ScrollView></SafeAreaView>;
}
export function Card({ title, detail, label }: { title: string; detail?: string; label?: string }) { return <View style={styles.card}>{label && <Text style={styles.eyebrow}>{label}</Text>}<Text style={styles.cardTitle}>{title}</Text>{detail && <Text style={styles.text}>{detail}</Text>}</View>; }
export function Action({ title, onPress, disabled }: { title: string; onPress(): void; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[styles.button, disabled && { opacity: 0.5 }]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
export function Field(props: TextInputProps) { return <TextInput placeholderTextColor="#7b887e" style={styles.input} {...props}/>; }
export const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#f4f6f3" }, content: { padding: 24, gap: 16, paddingBottom: 40 }, title: { fontSize: 34, fontWeight: "600", color: "#20352e", letterSpacing: -1 }, eyebrow: { fontSize: 10, fontWeight: "700", letterSpacing: 2, color: "#527364", textTransform: "uppercase" }, text: { color: "#637269", lineHeight: 23 }, card: { padding: 22, gap: 12, borderRadius: 14, backgroundColor: "white", borderColor: "#dde5dd", borderWidth: 1 }, cardTitle: { color: "#20352e", fontWeight: "600", fontSize: 20 }, button: { padding: 16, borderRadius: 9, backgroundColor: "#245d4b", alignItems: "center" }, buttonText: { color: "white", fontWeight: "600" }, input: { padding: 15, backgroundColor: "white", color: "#20352e", borderColor: "#cad6ce", borderWidth: 1, borderRadius: 9, fontSize: 16 }, error: { color: "#8c3628", backgroundColor: "#f8e8df", padding: 14, borderRadius: 8 }, workspaceList: { gap: 8, paddingVertical: 4 }, chip: { padding: 12, borderRadius: 8, backgroundColor: "#e8eee8" }, selected: { backgroundColor: "#cddfce" } });
